use File::HomeDir;
use Backticks;
use Win32;
use warnings;
my $homedir  = File::HomeDir->my_home;
$| = 1;
print "[!] Setting up local variables...";
sleep 2;
print "[+] Directory set to home directorty => $homedir;
print "[!] Fetching user...";
my $user = Win32::LoginUser;
sleep 1;
print "[+] User set to current user => $user";
my $log = "Log.txt";
print "[+] Log set to default => Log.txt";
sleep 1;
print "[!] All variables set up...";
sleep 2;
system("cls");